// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyBuddyBackend.Database;

namespace StudyBuddyBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191023214058_UsersInChat")]
    partial class UsersInChat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.Chat", b =>
                {
                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.HasKey("GroupName");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ChatGroupName")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ChatGroupName");

                    b.HasIndex("Username");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.Property<string>("Salt")
                        .HasColumnType("VARCHAR")
                        .HasMaxLength(255);

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.UserInChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ChatGroupName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ChatGroupName");

                    b.HasIndex("Username");

                    b.ToTable("UsersInChats");
                });

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.Message", b =>
                {
                    b.HasOne("StudyBuddyBackend.Database.Entities.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatGroupName");

                    b.HasOne("StudyBuddyBackend.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("StudyBuddyBackend.Database.Entities.UserInChat", b =>
                {
                    b.HasOne("StudyBuddyBackend.Database.Entities.Chat", "Chat")
                        .WithMany("Users")
                        .HasForeignKey("ChatGroupName");

                    b.HasOne("StudyBuddyBackend.Database.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("Username");
                });
#pragma warning restore 612, 618
        }
    }
}
